---
- name: Yum Install Packages
  yum: name={{item}} state=latest
  with_items:
     - wget
     - unzip

- name: terraform install
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip 
    dest: /usr/bin
    remote_src: True
