---

home: "/home/centos"

#secret data vaulted
gitlab_private_key: "{{ vault_gitlab_private_key }}"
docker_hub_login: "{{ vault_docker_hub_login }}"
docker_hub_email: "{{ vault_docker_hub_email }}"
docker_hub_password: "{{ vault_docker_hub_password }}"

target_host: localhost