---
# tasks file for server-base-config

- name: Configure the timezone
  timezone:
    name: "UTC"

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: create user
  user:
    name: "{{ deb_user }}"
    state: present
    groups: sudo
    shell: /bin/bash
    password: "{{ 'deb_password' | password_hash('sha512', 'deb_secretsalt') }}"

#Base configuration for Debian hosts
- name: Ensure basic packages are installed
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ list_packages }}"

- name: Install and configure NTP
  package:
    name: ntp
    state: present
  vars:
    ntpservers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org

- name: Set NTP servers
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
    - restart ntp
 
...