---
# tasks file for notify_server_info

- name: Gather server information
  ansible.builtin.setup:
    gather_subset:
      - all
  register: server_info

- name: Get server IP address
  set_fact:
    server_ip: "{{ ansible_default_ipv4.address }}"

- name: Get disk space information
  command: "df -h"
  register: disk_space

- name: Debug Server Facts
  ansible.builtin.debug:
    var: server_info

- name: Get /opt available disk space information
  command: "df -h /opt"
  register: disk_space_avail

- name: Debug Disk Space Facts
  ansible.builtin.debug:
    var: disk_space

- name: Check if the server is running
  shell: "echo 'Server is running'"
  ignore_errors: true
  register: server_running

- name: Create HTML table with server information
  template:
    src: "server_info_template.html.j2"
    dest: "{{ email_template_dest }}"
  delegate_to: localhost