---
# tasks file for notify_server_info

- name: "Collect Server Informations"
  import_tasks: "collect_server_info.yml"

- name: "Send Server Informations by email"
  import_tasks: "valo_email.yml"

- name: "Send server info by mail"
  import_tasks: "cleanup_files.yml"
  tags:
    - cleanup_files
