---
- name: Deploy traefik v2.5
  hosts: "{{ hosts }}"
  become: true
  tasks:
  - name: Deploy traefik
    become_user: "{{ lookup('env','USER') }}"
    community.docker.docker_container:
      name: traefik
      image: "traefik:v2.5"
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /etc/traefik:/etc/traefik
      restart_policy: unless-stopped
...