---
- name: Send Server Information via Slack
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather facts about target servers
      setup:
        filter: ansible_nodename

    - name: Create a JSON file with server information
      copy:
        content: |
          {
            "Servers": [
              {% for host in ansible_play_hosts %}
              {
                "Host": "{{ hostvars[host]['ansible_nodename'] }}",
                {% if hostvars[host]['ansible_mounts'] is defined %}
                "DiskSpace": "{{ hostvars[host]['ansible_mounts'][0]['size_available'] }}"
                {% else %}
                "DiskSpace": "N/A"
                {% endif %}
              }{% if not loop.last %},{% endif %}
              {% endfor %}
            ]
          }
        dest: /tmp/server_info.json

    - name: Send server information to Slack
      slack:
        token: "your_slack_api_token"
        channel: "#devops-trainings"
        msg: |
          Here is the list of up servers and their available disk space:

          ```{{ lookup('file', '/tmp/server_info.json') | to_json(indent=2) }}```
