---
############################ defaults file for docker_install ########################################

# Edition can be one of: 'ce' (Community Edition) or 'ee' (Enterprise Edition).
docker_edition: "ce"
docker_package: "docker-{{ docker_edition }}"
docker_package_state: present

# Service options.
docker_service_state: started
docker_service_enabled: true

# Docker Compose options.
docker_install_compose: true
docker_compose_version: "2.6.1"
docker_compose_path: /usr/local/bin/docker-compose
docker_compose_url: https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64

# Used only for Debian/Ubuntu. Switch 'stable' to 'edge' if needed.
docker_apt_release_channel: stable
docker_apt_arch: amd64
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
docker_apt_ignore_key_error: true

docker_dependencies_Debian:
  - apt-transport-https
  - ca-certificates

docker_old_versions_Debian:
  - docker
  - docker-engine
# apt key url
apt_key_url: "https://download.docker.com/linux/ubuntu/gpg"
apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"