---
# tasks file for debian-server-setup

- name: Update apt cache
  apt:
    update_cache: yes

- name: "Install prerequisites packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - python3-pip
    - python3-venv
    - git
    - curl
    - wget

- name: "Add a debian user"
  user:
    name: "{{ deb_user }}"
    state: present
    groups: sudo
    shell: /bin/bash
    password: "{{ 'deb_password' | password_hash('sha512', 'deb_secretsalt') }}"

...